server:
  port: 8081
    
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/admin-app-db?createDatabseIfNotExist=true&useUnicode=true&useJDBCCompliantTimezoneShift=true
    password: user
    username: user
    driverClassName: com.mysql.cj.jdbc.Driver
  application:
    name: admin-app
    
    
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true